### ISSUE TITLE
Basic authentication information is not passed through

### ISSUE THREAD

**Issue by daFish** [jensschulze/restinthemiddle#2]
**What do I expect?**

If the `TARGET_HOST_DSN` contains basic authentication information (e.g. `https://username:password@my-remote-host.net`) I expect them to be used for each middled request.

**What happens?**

Each request fails with an error code of 401.

**Comment by jensschulze** [comment]
Fixed in https://github.com/jensschulze/restinthemiddle/commit/904162da1a7217031f3a8072239ed8cd0dd71851
